# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetupGuide',
            new_name='SetupGuidePage',
        ),
    ]
