# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_guide', '0002_auto_20180207_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='lead_in',
            field=models.TextField(blank=True),
        ),
    ]
