# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_guide', '0004_auto_20180322_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setupguidelandingpage',
            old_name='heading_zh',
            new_name='heading_zh_cn',
        ),
        migrations.RenameField(
            model_name='setupguidelandingpage',
            old_name='lead_in_zh',
            new_name='lead_in_zh_cn',
        ),
        migrations.RenameField(
            model_name='setupguidelandingpage',
            old_name='sub_heading_zh',
            new_name='sub_heading_zh_cn',
        ),
        migrations.RenameField(
            model_name='setupguidepage',
            old_name='description_zh',
            new_name='description_zh_cn',
        ),
        migrations.RenameField(
            model_name='setupguidepage',
            old_name='heading_zh',
            new_name='heading_zh_cn',
        ),
        migrations.RenameField(
            model_name='setupguidepage',
            old_name='sub_heading_zh',
            new_name='sub_heading_zh_cn',
        ),
        migrations.RenameField(
            model_name='setupguidepage',
            old_name='subsections_zh',
            new_name='subsections_zh_cn',
        ),
    ]
