version: '2'

networks:
  djangonetwork:
      driver: bridge

services:
  postgres:
    image: postgres:12.3-alpine
    env_file: ./docker/.env-postgres.test
    networks:
      - djangonetwork

  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - "6379:6379"
    logging:
      driver: "none"
    networks:
      - djangonetwork

  sut:
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 120s

    command: ./docker/cmd-test.sh
    env_file: ./docker/.env.test
    restart: "no"
    networks:
      - djangonetwork

