version: '2'

networks:
    djangonetwork:
      driver: bridge

services:
  postgres:
    image: postgres:12.3-alpine
    env_file: ./docker/.env-postgres.test
    container_name: postgres
    networks:
      - djangonetwork


  redis:
    image: redis:alpine
    restart: on-failure
    ports:
        - "7777:7777"
    logging:
        driver: "none"
    networks:
      - djangonetwork
    
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: ./docker/cmd-webserver.sh dev
    ports: ["8014:8014"]
    env_file: ./docker/.env
    restart: "on-failure"
    networks:
      - djangonetwork
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

