# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='footer_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
