# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 11:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_auto_20180308_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='footer_secondary_nav',
            field=wagtail.core.fields.StreamField((('internal_link', wagtail.core.blocks.PageChooserBlock()), ('external_link', wagtail.core.blocks.StructBlock((('link', wagtail.core.blocks.URLBlock(max_length=255)), ('text', wagtail.core.blocks.CharBlock(max_length=255)))))), blank=True),
        ),
    ]
