# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_auto_20180308_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='beta_bar_text',
            field=wagtailmarkdown.fields.MarkdownField(default=''),
        ),
        migrations.AddField(
            model_name='branding',
            name='is_beta',
            field=models.BooleanField(default=True),
        ),
    ]
