# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 15:43
from __future__ import unicode_literals

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_auto_20180309_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='beta_bar_text',
            field=wagtailmarkdown.fields.MarkdownField(default='This is a new service - your feedback will help improve it.'),
        ),
    ]
