# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 14:29
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0003_sectorpage_show_on_frontpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorpage',
            name='pullout',
            field=wagtail.core.fields.StreamField((('content', wagtail.core.blocks.StructBlock((('text', wagtailmarkdown.blocks.MarkdownBlock()), ('stat', wagtail.core.blocks.CharBlock()), ('stat_text', wagtail.core.blocks.CharBlock())), max_num=1, min_num=0)),), blank=True),
        ),
    ]
