# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 15:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0004_auto_20180305_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorpage',
            old_name='show_on_frontpage',
            new_name='featured',
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsections',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))), ('location', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('info', wagtailmarkdown.blocks.MarkdownBlock()), ('map', wagtail.images.blocks.ImageChooserBlock())))))),
        ),
    ]
