# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformpage',
            name='heading_ar',
            field=models.CharField(default='Contact Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='heading_de',
            field=models.CharField(default='Contact Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='heading_en',
            field=models.CharField(default='Contact Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='heading_es',
            field=models.CharField(default='Contact Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='heading_fr',
            field=models.CharField(default='Contact Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='heading_ja',
            field=models.CharField(default='Contact Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='heading_pt',
            field=models.CharField(default='Contact Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='heading_zh',
            field=models.CharField(default='Contact Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackformpage',
            name='heading_ar',
            field=models.CharField(default='Feedback', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackformpage',
            name='heading_de',
            field=models.CharField(default='Feedback', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackformpage',
            name='heading_en',
            field=models.CharField(default='Feedback', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackformpage',
            name='heading_es',
            field=models.CharField(default='Feedback', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackformpage',
            name='heading_fr',
            field=models.CharField(default='Feedback', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackformpage',
            name='heading_ja',
            field=models.CharField(default='Feedback', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackformpage',
            name='heading_pt',
            field=models.CharField(default='Feedback', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackformpage',
            name='heading_zh',
            field=models.CharField(default='Feedback', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportissueformpage',
            name='heading_ar',
            field=models.CharField(default='Report Issue', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportissueformpage',
            name='heading_de',
            field=models.CharField(default='Report Issue', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportissueformpage',
            name='heading_en',
            field=models.CharField(default='Report Issue', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportissueformpage',
            name='heading_es',
            field=models.CharField(default='Report Issue', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportissueformpage',
            name='heading_fr',
            field=models.CharField(default='Report Issue', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportissueformpage',
            name='heading_ja',
            field=models.CharField(default='Report Issue', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportissueformpage',
            name='heading_pt',
            field=models.CharField(default='Report Issue', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportissueformpage',
            name='heading_zh',
            field=models.CharField(default='Report Issue', max_length=255, null=True),
        ),
    ]
