# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 16:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180129_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='how_we_help',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))),), blank=True),
        ),
    ]
