# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 17:27
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_how_we_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subsections',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
    ]
