# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180309_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_lead_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_title',
            field=models.CharField(default='Set up an overseas business in the UK', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sector_title',
            field=models.TextField(default='Discover UK Industries', max_length=255),
        ),
    ]
