# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180309_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='sector_lead_in',
        ),
    ]
