# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180309_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='heading_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_ar',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))), ('page_link', wagtail.core.blocks.StructBlock((('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock()))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_de',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))), ('page_link', wagtail.core.blocks.StructBlock((('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock()))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_en',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))), ('page_link', wagtail.core.blocks.StructBlock((('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock()))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_es',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))), ('page_link', wagtail.core.blocks.StructBlock((('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock()))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_fr',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))), ('page_link', wagtail.core.blocks.StructBlock((('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock()))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_ja',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))), ('page_link', wagtail.core.blocks.StructBlock((('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock()))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_pt',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))), ('page_link', wagtail.core.blocks.StructBlock((('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock()))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_title_ar',
            field=models.CharField(default='How we help', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_title_de',
            field=models.CharField(default='How we help', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_title_en',
            field=models.CharField(default='How we help', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_title_es',
            field=models.CharField(default='How we help', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_title_fr',
            field=models.CharField(default='How we help', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_title_ja',
            field=models.CharField(default='How we help', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_title_pt',
            field=models.CharField(default='How we help', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_title_zh',
            field=models.CharField(default='How we help', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_zh',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))), ('page_link', wagtail.core.blocks.StructBlock((('page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock()))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_title_ar',
            field=models.TextField(default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_title_de',
            field=models.TextField(default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_title_en',
            field=models.TextField(default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_title_es',
            field=models.TextField(default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_title_fr',
            field=models.TextField(default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_title_ja',
            field=models.TextField(default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_title_pt',
            field=models.TextField(default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_title_zh',
            field=models.TextField(default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_lead_in_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_lead_in_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_lead_in_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_lead_in_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_lead_in_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_lead_in_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_lead_in_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_lead_in_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_title_ar',
            field=models.CharField(default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_title_de',
            field=models.CharField(default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_title_en',
            field=models.CharField(default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_title_es',
            field=models.CharField(default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_title_fr',
            field=models.CharField(default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_title_ja',
            field=models.CharField(default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_title_pt',
            field=models.CharField(default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='setup_guide_title_zh',
            field=models.CharField(default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subsections_ar',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subsections_de',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subsections_en',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subsections_es',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subsections_fr',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subsections_ja',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subsections_pt',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subsections_zh',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
    ]
