# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_de', models.TextField(null=True)),
                ('content_es', models.TextField(null=True)),
                ('content_fr', models.TextField(null=True)),
                ('content_pt', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_ja', models.TextField(null=True)),
                ('content_zh_cn', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
