# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '14 - Call to action',
                'verbose_name_plural': '14 - Call to action',
            },
        ),
        migrations.CreateModel(
            name='KillerFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '2 - Killer Facts',
                'verbose_name_plural': '2 - Killer Facts',
            },
        ),
        migrations.CreateModel(
            name='MacroContextBetweenCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '3 - Macro Context',
                'verbose_name_plural': '3 - Macro Context',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarketLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RDandInnovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '9 - R&D and Innovation',
                'verbose_name_plural': '9 - R&D and Innovation',
            },
        ),
        migrations.CreateModel(
            name='RDandInnovationCaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '10 - Case Study',
                'verbose_name_plural': '10 - Case Study',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SectorInitiatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector', unique=True)),
            ],
            options={
                'verbose_name': '8 - Sector Initiatives',
                'verbose_name_plural': '8 - Sector Initiatives',
            },
        ),
        migrations.CreateModel(
            name='SectorLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SectorOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector', unique=True)),
            ],
            options={
                'verbose_name': '1 - Sector Overview',
                'verbose_name_plural': '1 - Sector Overview',
            },
        ),
        migrations.CreateModel(
            name='ServicesOfferedByDIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '13 - Services Offered',
                'verbose_name_plural': '13 - Services Offered',
            },
        ),
        migrations.CreateModel(
            name='TalentAndEducationBySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector', unique=True)),
            ],
            options={
                'verbose_name': '7.2 - Talent & Education (Sector)',
                'verbose_name_plural': '7.2 - Talent & Education (Sector)',
            },
        ),
        migrations.CreateModel(
            name='TalentAndEducationGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '7.1 - Talent & Education (Generic)',
                'verbose_name_plural': '7.1 - Talent & Education (Generic)',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '15 - Testimonials',
                'verbose_name_plural': '15 - Testimonials',
            },
        ),
        migrations.CreateModel(
            name='UKBusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '5 - Business Overview',
                'verbose_name_plural': '5 - Business Overview',
            },
        ),
        migrations.CreateModel(
            name='UKGeographicOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '6 - Geographic Overview',
                'verbose_name_plural': '6 - Geographic Overview',
            },
        ),
        migrations.CreateModel(
            name='UKMarketOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '4 - UK Market Overview',
                'verbose_name_plural': '4 - UK Market Overview',
            },
        ),
        migrations.AddField(
            model_name='rdandinnovationcasestudy',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector', unique=True),
        ),
        migrations.AddField(
            model_name='rdandinnovation',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector', unique=True),
        ),
        migrations.AddField(
            model_name='macrocontextbetweencountries',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Market', unique=True),
        ),
        migrations.AddField(
            model_name='killerfacts',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector', unique=True),
        ),
    ]
