# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectoroverview',
            name='footer_image',
            field=models.ImageField(default='image', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='footer_image_copy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='footer_image_copy_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='footer_image_copy_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='footer_image_copy_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='footer_image_copy_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='footer_image_copy_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='footer_image_copy_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='footer_image_copy_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='footer_image_copy_zh_cn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
