# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment_report', '0002_auto_20180426_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltoaction',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='frontpage',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='killerfacts',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='macrocontextbetweencountries',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='networkandsupport',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='rdandinnovation',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='rdandinnovationcasestudy',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='sectorinitiatives',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='sectoroverview',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='servicesofferedbydit',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='talentandeducationbysector',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='talentandeducationgeneric',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='ukgeographicoverview',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='ukmarketoverview',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='videocasestudy',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='whoishere',
            name='approved',
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='killerfacts',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killerfacts',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='killerfacts',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='killerfacts',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='macrocontextbetweencountries',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='macrocontextbetweencountries',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='macrocontextbetweencountries',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='macrocontextbetweencountries',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='networkandsupport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkandsupport',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='networkandsupport',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='networkandsupport',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rdandinnovation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rdandinnovation',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rdandinnovation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='rdandinnovation',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rdandinnovationcasestudy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rdandinnovationcasestudy',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rdandinnovationcasestudy',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='rdandinnovationcasestudy',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sectorinitiatives',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectorinitiatives',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sectorinitiatives',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sectorinitiatives',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicesofferedbydit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicesofferedbydit',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicesofferedbydit',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='servicesofferedbydit',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='talentandeducationbysector',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentandeducationbysector',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='talentandeducationbysector',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='talentandeducationbysector',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='talentandeducationgeneric',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentandeducationgeneric',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='talentandeducationgeneric',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='talentandeducationgeneric',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ukgeographicoverview',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ukgeographicoverview',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ukgeographicoverview',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='ukgeographicoverview',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='videocasestudy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocasestudy',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='videocasestudy',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='videocasestudy',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='whoishere',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whoishere',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='whoishere',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='whoishere',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
    ]
