# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0003_auto_20180411_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesofferedbydit',
            name='footer_image',
            field=models.ImageField(default='image', upload_to=''),
            preserve_default=False,
        ),
    ]
