# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0004_servicesofferedbydit_footer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAndSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
            ],
            options={
                'verbose_name': '9 - Network And Support',
                'verbose_name_plural': '9 - Network And Support',
            },
        ),
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'verbose_name': '15 - Call to action', 'verbose_name_plural': '15 - Call to action'},
        ),
        migrations.AlterModelOptions(
            name='rdandinnovation',
            options={'verbose_name': '10 - R&D and Innovation', 'verbose_name_plural': '10 - R&D and Innovation'},
        ),
        migrations.AlterModelOptions(
            name='rdandinnovationcasestudy',
            options={'verbose_name': '11 - Case Study', 'verbose_name_plural': '11 - Case Study'},
        ),
        migrations.AlterModelOptions(
            name='servicesofferedbydit',
            options={'verbose_name': '14 - Services Offered', 'verbose_name_plural': '14 - Services Offered'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': '16 - Testimonials', 'verbose_name_plural': '16 - Testimonials'},
        ),
    ]
