# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0005_auto_20180413_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkandsupport',
            name='background_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
