# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0006_auto_20180426_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltoaction',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='frontpage',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='killerfacts',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='macrocontextbetweencountries',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='networkandsupport',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='rdandinnovation',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='rdandinnovationcasestudy',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='sectorinitiatives',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='sectoroverview',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='servicesofferedbydit',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='talentandeducationbysector',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='talentandeducationgeneric',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='ukgeographicoverview',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='ukmarketoverview',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='videocasestudy',
            name='active_draft',
        ),
        migrations.RemoveField(
            model_name='whoishere',
            name='active_draft',
        ),
    ]
