# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('content_en', markdownx.models.MarkdownxField(null=True)),
                ('content_de', markdownx.models.MarkdownxField(null=True)),
                ('content_es', markdownx.models.MarkdownxField(null=True)),
                ('content_fr', markdownx.models.MarkdownxField(null=True)),
                ('content_pt', markdownx.models.MarkdownxField(null=True)),
                ('content_ar', markdownx.models.MarkdownxField(null=True)),
                ('content_ja', markdownx.models.MarkdownxField(null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
