# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0008_videocasestudy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='content_ja',
        ),
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='content_pt',
        ),
        migrations.RemoveField(
            model_name='ukbusinessinfo',
            name='content_zh_cn',
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='body_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
