# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-11 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0008_lastpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'verbose_name': '14 - Call to action', 'verbose_name_plural': '14 - Call to action'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '15 - Contact', 'verbose_name_plural': '15 - Contact'},
        ),
        migrations.AlterModelOptions(
            name='servicesofferedbydit',
            options={'verbose_name': '13 - Services Offered', 'verbose_name_plural': '13 - Services Offered'},
        ),
        migrations.AlterModelOptions(
            name='videocasestudy',
            options={'verbose_name': '11.1 Video case study', 'verbose_name_plural': '11.1 Video case study'},
        ),
    ]
