# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0009_auto_20180511_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkandsupport',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector'),
            preserve_default=False,
        ),
    ]
