# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0009_auto_20180416_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ukbusinessinfo',
            options={'verbose_name': '5 - Business Info', 'verbose_name_plural': '5 - Business Info'},
        ),
        migrations.AlterField(
            model_name='ukbusinessinfo',
            name='body_image',
            field=models.FileField(upload_to=''),
        ),
    ]
