# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0010_networkandsupport_sector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TalentAndEducationGeneric',
        ),
    ]
