# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0011_auto_20180416_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': '0 - Front Page',
                'verbose_name_plural': '0 - Front Page',
            },
        ),
    ]
