# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0011_delete_talentandeducationgeneric'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIRRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Market')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector')),
            ],
        ),
        migrations.AlterModelOptions(
            name='networkandsupport',
            options={'verbose_name': '10 - Network And Support', 'verbose_name_plural': '10 - Network And Support'},
        ),
        migrations.AlterModelOptions(
            name='rdandinnovation',
            options={'verbose_name': '9 - R&D and Innovation', 'verbose_name_plural': '9 - R&D and Innovation'},
        ),
    ]
