# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0012_frontpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoIsHere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': "12 - Who's here (background image)",
                'verbose_name_plural': "12 - Who's here (background image)",
            },
        ),
    ]
