# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0012_auto_20180517_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirrequest',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
