# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0013_pirrequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirrequest',
            name='pdf',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
