# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0014_auto_20180418_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector', unique=True),
            preserve_default=False,
        ),
    ]
