# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('investment_report', '0014_pirrequest_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirrequest',
            name='country',
            field=models.ForeignKey(default='AF', on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country'),
            preserve_default=False,
        ),
    ]
