# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0015_frontpage_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlogo',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investment_report.Market'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectorlogo',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='killerfacts',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='killerfacts',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='killerfacts',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='killerfacts',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='killerfacts',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='killerfacts',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='killerfacts',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='killerfacts',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='killerfacts',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='macrocontextbetweencountries',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='macrocontextbetweencountries',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='macrocontextbetweencountries',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='macrocontextbetweencountries',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='macrocontextbetweencountries',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='macrocontextbetweencountries',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='macrocontextbetweencountries',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='macrocontextbetweencountries',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='macrocontextbetweencountries',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='networkandsupport',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='networkandsupport',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='networkandsupport',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='networkandsupport',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='networkandsupport',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='networkandsupport',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='networkandsupport',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='networkandsupport',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='networkandsupport',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovation',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='rdandinnovation',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovation',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovation',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovation',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovation',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovation',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovation',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovation',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovationcasestudy',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='rdandinnovationcasestudy',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovationcasestudy',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovationcasestudy',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovationcasestudy',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovationcasestudy',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovationcasestudy',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovationcasestudy',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='rdandinnovationcasestudy',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectorinitiatives',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='sectorinitiatives',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectorinitiatives',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectorinitiatives',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectorinitiatives',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectorinitiatives',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectorinitiatives',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectorinitiatives',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectorinitiatives',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image',
            field=models.ImageField(help_text='Image at bottom of this page', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy',
            field=models.TextField(blank=True, help_text='Text overlayed on image'),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_ar',
            field=models.TextField(blank=True, help_text='Text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_attribution',
            field=models.TextField(blank=True, help_text='Smaller text overlayed on image'),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_attribution_ar',
            field=models.TextField(blank=True, help_text='Smaller text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_attribution_de',
            field=models.TextField(blank=True, help_text='Smaller text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_attribution_en',
            field=models.TextField(blank=True, help_text='Smaller text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_attribution_es',
            field=models.TextField(blank=True, help_text='Smaller text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_attribution_fr',
            field=models.TextField(blank=True, help_text='Smaller text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_attribution_ja',
            field=models.TextField(blank=True, help_text='Smaller text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_attribution_pt',
            field=models.TextField(blank=True, help_text='Smaller text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_attribution_zh_cn',
            field=models.TextField(blank=True, help_text='Smaller text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_de',
            field=models.TextField(blank=True, help_text='Text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_en',
            field=models.TextField(blank=True, help_text='Text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_es',
            field=models.TextField(blank=True, help_text='Text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_fr',
            field=models.TextField(blank=True, help_text='Text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_ja',
            field=models.TextField(blank=True, help_text='Text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_pt',
            field=models.TextField(blank=True, help_text='Text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='footer_image_copy_zh_cn',
            field=models.TextField(blank=True, help_text='Text overlayed on image', null=True),
        ),
        migrations.AlterField(
            model_name='servicesofferedbydit',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='servicesofferedbydit',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='servicesofferedbydit',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='servicesofferedbydit',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='servicesofferedbydit',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='servicesofferedbydit',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='servicesofferedbydit',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='servicesofferedbydit',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='servicesofferedbydit',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='servicesofferedbydit',
            name='footer_image',
            field=models.ImageField(help_text='Image at bottom of this page', upload_to=''),
        ),
        migrations.AlterField(
            model_name='talentandeducationbysector',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='talentandeducationbysector',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationbysector',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationbysector',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationbysector',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationbysector',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationbysector',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationbysector',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationbysector',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationgeneric',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='talentandeducationgeneric',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationgeneric',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationgeneric',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationgeneric',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationgeneric',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationgeneric',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationgeneric',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='talentandeducationgeneric',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='ukbusinessinfo',
            name='body_image',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", upload_to=''),
        ),
        migrations.AlterField(
            model_name='ukgeographicoverview',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='ukgeographicoverview',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='ukgeographicoverview',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='ukgeographicoverview',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='ukgeographicoverview',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='ukgeographicoverview',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='ukgeographicoverview',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='ukgeographicoverview',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='ukgeographicoverview',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='ukmarketoverview',
            name='body_image',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", upload_to=''),
        ),
        migrations.AlterField(
            model_name='videocasestudy',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor'),
        ),
        migrations.AlterField(
            model_name='videocasestudy',
            name='content_ar',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='videocasestudy',
            name='content_de',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='videocasestudy',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='videocasestudy',
            name='content_es',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='videocasestudy',
            name='content_fr',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='videocasestudy',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='videocasestudy',
            name='content_pt',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='videocasestudy',
            name='content_zh_cn',
            field=markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True),
        ),
    ]
