# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0016_auto_20180419_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorlogo',
            old_name='market',
            new_name='sector',
        ),
    ]
