# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('investment_report', '0017_auto_20180419_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='countries',
            field=models.ManyToManyField(to='countries_plus.Country'),
        ),
    ]
