# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0018_market_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='body_image_ar',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='body_image_de',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='body_image_en',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='body_image_es',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='body_image_fr',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='body_image_ja',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='body_image_pt',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukbusinessinfo',
            name='body_image_zh_cn',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='body_image_ar',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='body_image_de',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='body_image_en',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='body_image_es',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='body_image_fr',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='body_image_ja',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='body_image_pt',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='body_image_zh_cn',
            field=models.FileField(help_text="Fact sheet SVG overlayed on background of background. Don't edit unless you know what you are doing. Viewbox needs to be carefully calibrated here", null=True, upload_to=''),
        ),
    ]
