# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-20 13:04
from __future__ import unicode_literals

import config.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0018_auto_20180711_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirrequest',
            name='gdpr_optin',
            field=models.BooleanField(default=False),
        ),
    ]
