# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 10:05
from __future__ import unicode_literals

import config.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0019_auto_20180820_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='website_href',
            field=models.URLField(default='https://invest.great.gov.uk/contact/', help_text='Custom link for website (used for tracking)', max_length=255),
            preserve_default=False,
        )
    ]
