# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0024_sectorinitiatives_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowWeCanHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor')),
                ('content_en', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_de', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_es', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_fr', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_pt', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_ar', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_ja', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the right hand side', null=True, upload_to='')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector')),
            ],
            options={
                'verbose_name': '8 - How we can help',
                'verbose_name_plural': '8 - How we can help',
            },
        ),
        migrations.CreateModel(
            name='SmartWorkforceSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor')),
                ('content_en', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_de', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_es', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_fr', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_pt', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_ar', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_ja', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('content_zh_cn', markdownx.models.MarkdownxField(help_text='Markdown input. Please refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for intructions. Images may be dragged and droped into the editor', null=True)),
                ('sub_page', models.SmallIntegerField(default=0, help_text='For multiple sub-pages of this page, number them here. ')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the left panel', null=True, upload_to='')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector')),
            ],
            options={
                'verbose_name': '7.2 - Talent & Education (Sector)',
                'verbose_name_plural': '7.2 - Talent & Education (Sector)',
            },
        ),
    ]
