# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-01 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0025_howwecanhelp_smartworkforcesector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howwecanhelp',
            name='sector',
        ),
    ]
