# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-01 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0026_remove_howwecanhelp_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartworkforcesector',
            options={'verbose_name': '5. Smart Workforce', 'verbose_name_plural': '5. Smart Workforce'},
        ),
    ]
