# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0028_casestudysector'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudysector',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
