# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0030_auto_20201015_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallToAction',
        ),
        migrations.RemoveField(
            model_name='networkandsupport',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='rdandinnovation',
            name='sector',
        ),
        migrations.DeleteModel(
            name='ServicesOfferedByDIT',
        ),
        migrations.RemoveField(
            model_name='talentandeducationbysector',
            name='sector',
        ),
        migrations.DeleteModel(
            name='UKBusinessInfo',
        ),
        migrations.DeleteModel(
            name='UKGeographicOverview',
        ),
        migrations.DeleteModel(
            name='NetworkAndSupport',
        ),
        migrations.DeleteModel(
            name='RDandInnovation',
        ),
        migrations.DeleteModel(
            name='TalentAndEducationBySector',
        ),
    ]
