# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0032_auto_20201022_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_color', models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True)),
                ('background_image', models.FileField(upload_to='')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_report.Sector')),
            ],
            options={
                'verbose_name': '0 - Table of Contents',
                'verbose_name_plural': '0 - Table of Contents',
            },
        ),
        migrations.AddField(
            model_name='casestudysector',
            name='header_color',
            field=models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='header_color',
            field=models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='howwecanhelp',
            name='header_color',
            field=models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='killerfacts',
            name='header_color',
            field=models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='lastpage',
            name='header_color',
            field=models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='macrocontextbetweencountries',
            name='header_color',
            field=models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sectorinitiatives',
            name='header_color',
            field=models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sectoroverview',
            name='header_color',
            field=models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='smartworkforcesector',
            name='header_color',
            field=models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='ukmarketoverview',
            name='header_color',
            field=models.CharField(help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
    ]
