# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0033_auto_20201127_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudysector',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='contentspage',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='howwecanhelp',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='killerfacts',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='lastpage',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='macrocontextbetweencountries',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sectorinitiatives',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sectoroverview',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='smartworkforcesector',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ukmarketoverview',
            name='header_color',
            field=models.CharField(blank=True, help_text='Overide default header text colour (for dark backgrounds)', max_length=16, null=True),
        ),
    ]
