# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0034_auto_20201127_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketlogo',
            name='market',
        ),
        migrations.RemoveField(
            model_name='sectorlogo',
            name='sector',
        ),
        migrations.DeleteModel(
            name='MarketLogo',
        ),
        migrations.DeleteModel(
            name='SectorLogo',
        ),
    ]
