# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0035_auto_20201217_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_display_link', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_url', models.CharField(blank=True, max_length=500, null=True)),
                ('email_address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment_report.Market')),
            ],
        ),
    ]
