# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0036_marketcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcontact',
            name='first_title',
            field=models.CharField(blank=True, help_text='Title appearing only on the first contact box', max_length=250, null=True),
        ),
    ]
