# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-05 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_report', '0038_auto_20201218_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirrequest',
            name='accessible',
            field=models.BooleanField(default=False),
        ),
    ]
