# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 18:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_svgmap.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionpage',
            name='subsections',
            field=wagtail.core.fields.StreamField((('content', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))), ('location', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('info', wagtailmarkdown.blocks.MarkdownBlock()), ('map', wagtail.core.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))), null=True, on_delete=django.db.models.deletion.CASCADE))))))),
        ),
    ]
