# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 14:43
from __future__ import unicode_literals

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='content_ar',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='content_de',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='content_en',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='content_es',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='content_fr',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='content_ja',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='content_pt',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='content_zh',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
    ]
