# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180322_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infopage',
            old_name='content_zh',
            new_name='content_zh_cn',
        ),
    ]
